services:
  mongodb1:
    image: mongo
    container_name: mongodb1
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb1:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  zookeeper:
    image: bitnami/zookeeper
    ports:
      - 2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-0:
    image: bitnami/kafka
    hostname: kafka-0
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper